### ISSUE TITLE
Use xmlstarlet instead of sed

### ISSUE THREAD

**Issue by ypid** [punktDe/vagrant-opnsense#2]
`xmlstarlet` could be used to edit the XML file.

I am currently not using your Vagrant. Your project just scrolled through my news feed and I thought I could leave you this feedback. If you like editing XML with sed, you can close this issue. I guess it works :)

Ref: https://github.com/punktDe/vagrant-opnsense/blob/main/Vagrantfile

**Comment by pmhausen** [comment]
Thanks for the hint. I will look into this when I find some time. Reliably editing XML instead of guesswork and praying there are no other identical lines in the file would open up new opportunities for more/better customization.

For the moment you guessed correct: it works ;)

**Comment by pmhausen** [comment]
I have had a closer look into the matter yesterday and decided to keep the project using sed for now. Problem is that I cannot  install packages like xmlstarlet before bootstrapping OPNsense because the bootstrap routine deletes all present packages first. After bootstrapping the system is connected to the OPNsense package repo and not the standard FreeBSD one. And xmlstarlet is simply not available there.

In case I need to do more complex multi line changed I will probably have to resort to awk.

Thanks for your suggestion, though. I will close this issue.
